version: "3"

services:
  kaspad1:
    container_name: kaspad1
    image: karlsennetwork/kaspad:v0.11.11_1
    restart: unless-stopped
    volumes:
      - kaspad1:/app/data/
#    command: /app/kaspad --utxoindex --enablebanning --whitelist=192.168.1.0/24

  kaspad2:
    container_name: kaspad2
    image: karlsennetwork/kaspad:v0.11.11_1
    restart: unless-stopped
    volumes:
      - kaspad2:/app/data/
#    command: /app/kaspad --utxoindex --enablebanning --whitelist=192.168.1.0/24

  kaspad_loadbalancer:
    container_name: kaspad_loadbalancer
    image: karlsennetwork/kaspad_loadbalancer:v0.11.11_1
    restart: unless-stopped
    ports:
      - "9000:9000/tcp"
      - "42110:42110/tcp"
      - "42111:42111/tcp"

volumes:
  kaspad1:
  kaspad2:

